## The setting

$$
y_l = x_l\beta + e_l
$$

$\mathbb{E}[e_l|x_l]=0$, and $(y_l, x_l, e_l)$ are associated with observed spatial location $s_l \in \mathbb{R}^d$. Spatial location in time is $d=1$, two dimensions, like in altitude and latitude, $d=2$, and so on. 

$e_l$ is generated by a Gaussian process with covariance function $cov(e_l,e_{l'})=\exp(-c||s_l-s_{l'}||)$, where $s_l$ and $s_{l'}$ denote the spatial locations of $e_l$ and $e_{l'}$, and $c>0$ is a parameter that governs the strength of the spatial correlation. The value of $c$ is calibrated to induce a specific average pairwise correlation $\bar{\rho}=[n(n-1)]^{-1}\sum_{l,l'\not=l}cov(e_l,e_{l'})$. In other words, $c=c_{\bar{\rho}}$ solves $[n(n-1)]^{-1}\sum_{l,l'\not=l}\exp(-c_{\bar{\rho}}||s_l-s_{l'}||)=\bar{\rho}$.

Let $\Sigma(c)$ be the covariance matrix of $e_l$ evaluated at the sample locations, so that $\Sigma(c)_{l,l'}=\exp(-c||s_l-s_{l'} ||)$, and let $\bar{\rho}(c)$ denote the resulting average pairwise correlation $\bar{\rho}(c)=[n(n-1)]^{-1}\sum_{l,l'\not=l}\Sigma(c)_{l,l'}$. If the researcher desires a test that controls size for values of $\bar{\rho}$ as large as $\bar{\rho}_{max}$, then he can choose $c_{min}$ such that $\bar{\rho}(c_{min})=\bar{\rho}_{max}$. Then, $\Sigma(c_{min})$ is the **worst case** covariance matrix in the sense that it induces the largest value of $\sigma^2$ among all $\Sigma(c)$ with $\bar{\rho}\le \bar{\rho}_{max}$