## Covariance structure

@fig-dist-cov to -@fig-extras show graphically the covariance structure of the DGP, in particular with respect to locations and distance.

```{r}
#| label: tbl-sum-stats
#| tbl-cap: Summary statistics of the error term
#| output: asis
#| echo: false
#| warning: false
#| error: false
#| include: false


load("../Simulations/Products/plots.RData")

kbl(five_num, booktabs=TRUE, col.names =c("$e_l$"), escape=F)
# five_num

```


```{r}
#| label: fig-dist-cov
#| fig-align: center
#| fig-cap: Distance vs Covariance
#| echo: false
#| warning: false

load("../Simulations/Products/plots.RData")

with(
    df_plot,
    plot(distance,cov)
)
```

```{r}
#| label: fig-cov-hist
#| fig-align: center
#| fig-cap: Covariance histogram
#| echo: false
#| warning: false

with(
    df_plot[df_plot$distance!=0 & df_plot$cov<1 & df_plot$cov>0.01,],
    # hist(distance,breaks=100, freq=TRUE)
    hist(cov, breaks=50,freq=T, main=NULL)
)
```

```{r}
#| label: fig-extras
#| fig-align: center
#| fig-cap: Distance and location histograms
#| fig-subcap: 
#|  - Distance
#|  - Locations
#| layout-ncol: 2
#| echo: false
#| warning: false

with(
    df_plot,
    hist(distance,freq=TRUE, main=NULL)
    # hist(cov, breaks=300, freq=T)
)

with(
    df_plot,
    hist(s_1,freq=TRUE, main=NULL)
    # hist(cov, breaks=300, freq=T)
)
```