## Set up ####

library(knitr)
library(tidyverse)
# opts_knit$set(
#     echo = FALSE,
#     fig_path()
# )

library(kableExtra)
# options(
#     knitr.table.format = "latex",
#     knitr.kable.NA = "")

# products_folder <- "../Simulations/Products/" # In quarto
products_folder <- "Simulations/Products/" # In R

excercise <- "light_locs_me_3p_optimal_CI"

## Reading data generated by Matlab ####
e_ar1_tbl <- read.csv(
    paste0(products_folder, "opt_spline_sims_ar1_", excercise, ".csv")
)

optimal_CI_table <- read.csv(
    paste0(products_folder, "opt_ci_table_", excercise, ".csv")
)
splines_table <- read.csv(
    paste0(products_folder, "splines_damians_d_", excercise, ".csv")
)

## Arranging the data ####
damians_d <-splines_table %>%
    summarise(
        across(
            starts_with("DD"),
            mean
        )
    )

splines_table %>%
    summarise(
        across(
            everything(),
            mean
        )
    )

notes <- c(rep("",12), round(damians_d[[1]], digits = 3),round(damians_d[[2]], digits = 3))

row_names_kernel<- c(
    "HR",
    "SCPC",
    "C-SCPC",
    "Kernel 0.015",
    "Kernel 0.030",
    "Kernel 0.050",
    "Kernel 0.070",
    "HR",
    "Kernel 0.015",
    "Kernel 0.030",
    "Kernel 0.050",
    "Kernel 0.070",
    "D's x2 ",
    "D's x3 "
)

row_names_kernel_notes <-paste0(row_names_kernel,notes)
row_names_kernel_notes

