---
title: "Spatial correlation"
format:
    pdf:
        documentclass: article
        colorlinks: true
        include-in-header: packages.tex
        keep-tex: true
        resource-path: 
            - "Simulations/Products"
        latex-output-dir: Output
number-sections: true
author: Hans Martinez
date: today
bibliography: biblio.bib
---

```{r}
#| label: setup
#| tbl-cap: "Rejection frequencies"
#| echo: false
#| warning: false

library(knitr)
# opts_knit$set(
#     echo = FALSE,
#     fig_path()
# )

library(kableExtra)
options(
    knitr.table.format = "latex",
    knitr.kable.NA = "")

```

## Updates {-}

- @tbl-pc shows the rejection frequencies for the optimal number of PCs of the 64 B-Spline for orders 1 and 2. Selecting the number of PCs using BIC. Spatial DGP.

- @fig-gamma-pc shows the distribution of $\gamma$, the residuals AR(1) slope coefficient. @fig-pc shows the distribution of the number of PCs selected in the simulations.

- @tbl-gamma displays the rejection frequencies for the optimal number of splines for a spatial DGP. The optimal number of splines was selected as the number of splines for which the OLS residuals produced the lowest AR(1) slope coefficient. @tbl-gamma-ts displays the rejection frequencies for this same exercise but using time series DGP.

- @fig-gamma-nsplines and [-@fig-gamma-nsplines-ts] display the distribution of the residuals' AR(1) slope coefficient that was used to select the number of splines; for the spatial and time series DGPs.

- @tbl-bic-ts displays the rejection frequencies for the optimal number of splines where the optimal number of splines was selected as the number of splines for which the OLS residuals produced the lowest Hansen's BIC ([@eq-hansen-bic]) using a time series DGP.

- @fig-gamma-bic and [-@fig-gamma-bic-ts] show the distribution of the residuals' AR(1) slope coefficient that resulted from selecting the optimal number of splines using the BIC criteria, for the spatial and time series DGPs.

## To-Do {-}

- Use Principal components from a matrix of 64 splines, coarse grid 4, 12,..., 64, select the number of PC's using BIC after sorting them
- Evenly distributed locations: SCPC adjusting $\bar\rho$ to avoid crashing.
- Power curves for the SCPC and C-SCPC methods.
- Cluster version of Kernel estimator.
- Measurement error in the locations.
    a.	Get rejection freq.
    b.	Plot distances (true vs. mismeasured).


<!-- PC -->
{{< include sections/120-pc.qmd >}}

<!-- AR(1) n spline selection-->
{{< include sections/110-gamma.qmd >}}

<!-- BIC n spline selection-->
{{< include sections/100-bic.qmd >}}

<!-- Kernel -->
{{< include sections/051-kernel.qmd >}}

<!-- Evenly spaced -->
{{< include sections/081-grid.qmd >}}




<!-- Locations and distances
{{< include sections/090-locs.qmd >}} -->


<!-- Kernel
{{< include sections/055-kernel-m1v2.qmd >}}-->

<!-- Step by step
{{< include sections/005-step-by-step.qmd >}} -->

<!-- BSplines and the error
{{< include sections/060-e-ar1.qmd >}} -->

<!-- Replication -->
<!-- {{< include sections/020-replication.qmd >}} -->

<!-- Intro -->
<!---
 {{< include sections/010-intro.qmd >}} 
--->

<!-- Plots
{{< include sections/040-e_l.qmd >}} -->

<!-- Power
{{< include sections/920-power.qmd >}} -->

<!-- Rejection prob
{{< include sections/910-rej-prob.qmd >}} -->

<!-- Follow-up
{{< include sections/900-followup.qmd >}}



<!-- Setting -->
{{< include sections/030-setting.qmd >}}

<!-- Worst case covariance function
{{< include sections/800-worst-cov.qmd >}} -->

<!-- Lit Rev -->
{{< include sections/00-lit-rev.qmd >}}


## References {-}

::: {#refs}
:::