# The Data Generating Process

The DGP process used in these simulations is as follows. 

$$
\begin{aligned}
    y_l, x_l &\sim (1-\rho)\epsilon_l +\rho \eta_l \\
    \epsilon_l &\sim N(0,1) \\
    \eta_l &\sim \mathcal{G}(\theta)
\end{aligned}
$$ 

$(y_l,x_l,\epsilon_l,\eta_l)$ are associated with observed spatial location $s_l \in \mathbb{R}^2$. $\epsilon$ is a white noise independent of $s_l$. $\eta$ is generated by a Gaussian process with covariance function $cov(s_l,s_{l'})=\exp(-\theta^{-1}||s_l-s_{l'}||)$. The parameter $\rho\in[0,1)$ controls the spatial correlation of observations.

# Simulations

In the simulations, the regression model is

$$
    y_l=\beta x_l + u_l
$$

because $y_l$ and $x_l$ are independent draws from the same DGP, the true parameter is $\beta=0$. The parameter of the gaussian process was set as $\theta=\sqrt{2}/10$. **500** observations were drawn of each variable $(y_l,x_l,s_l)$. Locations $s_l$ were drawn from the uniform Poisson process inside the unit square, two for each observation. The rejection frequencies are the fraction of the **1000** simulations that the the null hypothesis $H_0: \beta=0$ was rejected in favor of the alternative $H_1: \beta\not=0$.

# Spatial vs. Time Series correlation {#sec-ar1}

For reference, when $\rho=1$, the average of the elements of the variance-covariance matrix resulting from the covariance function $cov(s_l,s_{l'})=\exp(-\theta^{-1}||s_l-s_{l'}||)$ with $\theta=\sqrt{2}/10$ is 0.0839. This value is approximately equivalent to an AR(1) process with a slope of ~0.96.

The following table shows the average of the elements of the variance-covariance matrix of an AR(1) process with different values of autocorrelation, $\delta$. That is, for a value of $\delta$ and $T$ observations, the var-cov matrix will look like the following:

$$
    V = \begin{pmatrix}
    1 & \delta & \delta^2 & \cdots & \delta^{T-1} \\
    \delta & 1 & \delta & \cdots & \delta^{T-2} \\
    \delta^2 & \delta & 1 & \cdots & \delta^{T-3} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    \delta^{T-1} & \delta^{T-2} & \delta^{T-3} & \cdots & 1
    \end{pmatrix}
$$


| $\delta$ |   Average   |
|-------|-----------|
| 0.94  | 0.0626  |
| 0.95  | 0.0750   |
| 0.96  | 0.0932    |
| 0.97  | 0.1227  |


